import matplotlib.pyplot as plt
import pandas as pd

data = pd.read_csv("commits_with_rectified_msgs.csv", escapechar='\\')
need = data['rectified message']
a, b, c = 0, 0, 0

for x in need:
    if "Human" in x:
        a += 1
    elif "LLM" in x:
        b += 1
    else:
        c += 1

labels = ['Human-written', 'Generated-by T5 LLM', 'Newly-Generated by qwen']
sizes = [a, b, c]

plt.figure()
plt.pie(sizes, labels=labels, autopct='%1.1f%%', colors=['lightblue', 'lightsalmon', 'lightgreen'])
plt.title('Share of Rectified Messages')
plt.show()